### ISSUE TITLE
Error when running a Spring Boot JUnit-Test

### ISSUE THREAD

**Issue by Alan47** [jacoco/eclemma#102] opened 2015-07-07 12:50 UTC
Hello,

I've been using EclEmma for a very long time now and I was always extremely happy with it. Unfortunately, in my latest project it's acting up on me. When I try to run a JUnit-Test Coverage in Eclipse, where the test in question is executed by Spring / Spring Boot, then I get the following error message:

    No coverage data has been collected during this coverage session.

    Please do not terminate the Java process manually from Eclipse.

Well... I didn't do that. The JUnit-Test succeeded and terminated regularly. Closing this message reveals yet another message:

    'com.mountainminds.eclemma.internal.core.launching.AgentServer' has encountered a problem.

    Error while dumping coverage data (code 5013).

I've asked Google about this problem, apparently there is no real solution for it. I am using Eclipse 4.4.2, with the Spring Tool Suite 3.7.0 installed, on a Windows 8.1, 64bit, and a JDK 1.8.0_25.

I have tried both the EclEmma plugin from the Eclipse Marketplace and from `http://download.eclipselab.org/eclemma/trunk/update`, but both show the same behaviour.

Is there any workaround or any way to fix this?

**Comment by marchof** [comment] 2015-11-17 15:38
@Alan47 Sorry for the late reply. Did the problem resolve in the meantime?

Probably it is related to the way how the Spring Tool Suite terminates unit tests. We've seen simple code snippets that cause the same problem with the JUnit test runner, see #64

**Comment by marchof** [comment] 2015-12-07 05:51
Probably duplicate of #64.

**Closed by marchof** 2015-12-07 05:51 UTC
Labels: duplicate
