### ISSUE TITLE
error while loading coverage session(code 5001)

### ISSUE THREAD

**Issue by suhailjain** [jacoco/eclemma#131] opened 2016-10-27 07:00 UTC
### Steps to reproduce

EclEmma version: 2.3.3
Eclipse version: Luna Release (4.4.0)
Operating system: Windows 7 enterprise SP1.
### Expected behaviour

to show the code coverage for the executed java class file.
### Actual behaviour

Error while loading coverage session (code 5001).
Error while analyzing package fragment root test at F/Project/bin (code 5007).
Error while analyzing Y.class.

**Comment by marchof** [comment] 2016-10-27 09:57
Can you please provide the **full** stack trace from the Eclipse log file. It can be found at

```
<workspacedir>/.metadata/.log
```

Thx.

**Comment by suhailjain** [comment] 2016-10-28 06:25
[.log.zip](https://github.com/jacoco/eclemma/files/557700/default.log.zip)

here is the log file

**Comment by marchof** [comment] 2016-10-28 07:09
Are you sure this is the correct log file? There is no EclEmma exception in there

**Comment by suhailjain** [comment] 2016-10-28 07:34
yes, i picked this file from the directory you specified.

**Comment by marchof** [comment] 2016-10-28 07:45
Hm. Can you please open the "Error Log" view after the problem happened and see whether there is an entry?

**Comment by suhailjain** [comment] 2016-10-28 08:44
here is the entry from the "Error Log" view
[ErrorLogView.zip](https://github.com/jacoco/eclemma/files/557928/ErrorLogView.zip)

**Comment by marchof** [comment] 2016-10-28 08:48
Ah. Here we go. Aren't there more lines? It got clipped where interesting part starts:-(

```
eclipse.buildId=4.4.0.I20140606-1215
java.version=1.8.0_91
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

com.mountainminds.eclemma.core
Error
Fri Oct 28 13:16:42 IST 2016
Error while loading coverage session (code 5001).

org.eclipse.core.runtime.CoreException: Error while analyzing package fragment root test at F/drms/bin (code 5007).
    at com.mountainminds.eclemma.internal.core.analysis.PackageFragementRootAnalyzer.analyzeInternal(PackageFragementRootAnalyzer.java:78)
    at com.mountainminds.eclemma.internal.core.analysis.PackageFragementRootAnalyzer.analyze(PackageFragementRootAnalyzer.java:50)
    at com.mountainminds.eclemma.internal.core.analysis.SessionAnalyzer.processPackageFragmentRoot(SessionAnalyzer.java:100)
    at com.mountainminds.eclemma.internal.core.analysis.SessionAnalyzer.processSession(SessionAnalyzer.java:80)
    at com.mountainminds.eclemma.internal.core.JavaCoverageLoader$LoadSessionJob.run(JavaCoverageLoader.java:82)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.IOException: Error while analyzing DerControlAreaAggregationFacadeImplTest.class.
    at org.jacoco.core.analysis.Analyzer.analyzerError(Analyzer.java:153)
    at org.jacoco.core.analysis.Analyzer.analyzeClass(Analyzer.java:147)
    at org.jacoco.core.analysis.Analyzer.analyzeAll(Analyzer.java:178)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walkResource(ResourceTreeWalker.java:62)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walkResource(ResourceTreeWalker.java:74)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walkResource(ResourceTreeWalker.java:74)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walkResource(ResourceTreeWalker.java:74)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walkResource(ResourceTreeWalker.java:74)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walkResource(ResourceTreeWalker.java:74)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walkResource(ResourceTreeWalker.java:74)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walkResource(ResourceTreeWalker.java:74)
    at com.mountainminds.eclemma.internal.core.analysis.ResourceTreeWalker.walk(ResourceTreeWalker.java:50)
    at com.mountainminds.eclemma.internal.core.analysis.PackageFragementRootAnalyzer.analyzeInternal(PackageFragementRootAnalyzer.java:73)
    ... 5 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by suhailjain** [comment] 2016-10-28 08:54
haha i think this file would contain the rest.
[code5007.zip](https://github.com/jacoco/eclemma/files/557958/code5007.zip)

**Comment by marchof** [comment] 2016-10-28 09:37
Still clipped after `Caused by: java.lang.ArrayIndexOutOfBoundsException`

**Comment by suhailjain** [comment] 2016-10-29 04:42
but that is all i have in my error log.

**Comment by suhailjain** [comment] 2016-10-29 04:50
what can i help you with now, so that you could help me out !

**Comment by Godin** [comment] 2016-10-29 05:38
@suhailjain in this case maybe you can provide `DerControlAreaAggregationFacadeImplTest.class` ?

**Comment by suhailjain** [comment] 2016-11-01 07:10
sorry but that file contains confidential business logic.

**Comment by Godin** [comment] 2016-11-01 09:28
@suhailjain I'm afraid that without stack trace and without reproducer there is nothing what we can do here for you.

The only traces of `ArrayIndexOutOfBoundsException` in past were related to support of Java 8, but this has been fixed long time ago in EclEmma version 2.3.2, so please make sure that you are really using version **2.3.3** and try to find stack trace or try to create reproducer without confidential information.

Thank you for your understanding.

**Comment by marchof** [comment] 2016-11-01 12:35
@suhailjain If we would produce a simple Java program for you: Could you run that programm on your class? The error message might help to fix.

Alternatively I could give you a private communication channel to provide this class for testing only.

**Comment by suhailjain** [comment] 2016-11-02 04:56
surely i would run the program on my class @marchof

**Comment by marchof** [comment] 2016-11-02 22:02
@suhailjain Please unzip [analyze-test.jar.zip](https://github.com/jacoco/eclemma/files/567805/analyze-test.jar.zip) and run the JAR on your class files:

`java -jar analyze-test.jar your_classes_dir`

It should print successfully analyzed classes or give an stack trace.

**Comment by Godin** [comment] 2016-11-11 20:23
@suhailjain you had time to do what @suhailjain requested?

**Comment by Godin** [comment] 2016-11-18 20:23
@marchof in absence of feedback I'm tempted to close this - the longer the latency, the harder it will be to reproduce and provide required information matching initial conditions.

@suhailjain to get an impression about speed and depth of investigations in presence of proper information - you can have a look for example at `https://github.com/jacoco/jacoco/issues/394` and `https://github.com/jacoco/jacoco/issues/462`

**Comment by marchof** [comment] 2016-11-21 18:12
@suhailjain there is nothing we do here without your feedback. Sorry.

**Closed as completed by marchof** 2016-11-21 18:12 UTC
Labels: bug, feedback pending

**Comment by Godin** [comment] 2016-11-21 18:35
BTW @marchof I'm wondering if you know a concrete example, when "Error Log" View is not sufficient to get details of exception and required to look into log file? Maybe we can improve something here?

**Comment by marchof** [comment] 2016-11-21 18:42
@Godin we could enforce an exception somewhere deep down in class file processing (e.g. by truncating al class file on disk) and check whether the stack trace in Eclipse log is sufficient.

**Comment by Godin** [comment] 2016-11-21 18:43
@marchof yep - I had an idea to simulate JaCoCo failure, just thought that you might already know without this simulation.

**Comment by marchof** [comment] 2016-11-21 18:48
@Godin No, nothing specific. But I think we have seen incomplete stack traces before.

**Comment by Godin** [comment] 2016-11-21 18:49
@marchof ok, deal, I'll add this to the list of todo's for tests

**Comment by Godin** [comment] 2017-02-09 08:23
@marchof FYI:

I tried
```java
package p1.p2.p3;

import java.io.File;
import java.io.FileOutputStream;

import org.junit.Test;

public class TruncateTest {
	@Test
	public void test() throws Exception {
		File file = new File("bin/p1/p2/p3/TruncateTest.class");
		FileOutputStream fos = new FileOutputStream(file, true);
		fos.getChannel().truncate(file.length() - 1);
		fos.close();
	}
}
```
and ArrayIndexOutOfBoundsException has stack trace.

So the only cause of missing stack trace which I can imagine - is optimization in JVM:
```java
package org.jacoco.core.analysis;

import org.jacoco.core.data.ExecutionDataStore;
import org.jacoco.core.internal.instr.InstrSupport;
import org.jacoco.core.test.TargetLoader;
import org.junit.Before;
import org.junit.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;

import java.io.IOException;

public class OmitStackTraceInFastThrowTest {

	private Analyzer analyzer;

	@Before
	public void setup() {
		analyzer = new Analyzer(new ExecutionDataStore(),
				new ICoverageVisitor() {
					public void visitCoverage(IClassCoverage coverage) {
					}
				});
	}

	/**
	 * Without -XX:-OmitStackTraceInFastThrow shows
	 * ArrayIndexOutOfBoundsException without stack trace.
	 */
	@Test
	public void test() throws IOException {
		byte[] original = TargetLoader
				.getClassDataAsBytes(OmitStackTraceInFastThrowTest.class);
		byte[] truncated = new byte[original.length - 1];
		System.arraycopy(original, 0, truncated, 0, truncated.length);

		for (int i = 0; i < 50000; i++) {
			try {
				new ClassReader(truncated)
						.accept(new ClassVisitor(InstrSupport.ASM_API_VERSION) {
						}, 0);
			} catch (Exception ignore) {
			}
		}

		try {
			analyzer.analyzeClass(truncated, "Truncated.class");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

}
```
